home:
  path: /
  controller: App\Controller\HomeController::home

#PRODUCT
show_product:
  path: /product/{id}
  controller: App\Controller\ProductController::show_product

#CART
show_cart:
  path: /cart
  controller: App\Controller\CartController::show_cart

add_to_cart:
  path: /add_to_cart/{product_id}
  controller: App\Controller\CartController::add_to_cart